old_books/urls.py
from django.contrib import admin
from django.urls import path,re_path
from app01 import views
from django.views.static import serve
from old_books import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/',views.index ),
    path('',views.home ),
    path('home/',views.home ),
    path('search/',views.search ),
    re_path('book_detail/(?P<id>\d+)$',views.book_detail ),
    path('category/',views.category ),
    path('shop_car/',views.shop_car ),
    path('sell_book/',views.sell_book ),
    path('sell_in/',views.sell_in ),
    re_path('sell_in_del/(?P<id>\d+)$',views.sell_in_del ),
    re_path('sell_in_edit/(?P<id>\d+)$',views.sell_in_edit ),
    path('login/',views.login ),
    path('logout/',views.logout ),
    path('register/',views.register ),
    path('my_zone/',views.my_zone ),
    path('my_zone/sell_books/',views.my_zone ),
    path('my_balance/',views.my_balance ),
    path('my_bookrack/', views.my_bookrack),
    path('my_zone_info/', views.info),
    path('diggit/', views.diggit),
    re_path('comment_reply/(?P<book_id>\d+)/(?P<comt_id>\d+)/$', views.comment_reply),
    re_path('appraise/(?P<book_id>\d+)/$', views.appraise),
    re_path('shipping_car/(?P<id>.*)$', views.shipping_car),
    re_path('shopping_car_del/(?P<id>.*)$', views.shopping_car_del),
    re_path(r"media/(?P<path>.*)$", serve, {"document_root": settings.MEDIA_ROOT}),

]

app01/models.py
from django.db import models
from old_books import settings

from django.contrib.auth.models import AbstractUser
class UserInfo(AbstractUser):
    """
    用户信息
    """
    nid = models.AutoField(primary_key=True)
    balance = models.IntegerField(verbose_name='用户余额',null=True)

class Category(models.Model):
    cid = models.AutoField(primary_key=True)
    title = models.CharField(verbose_name="文章分类",max_length=32,null=True)


class Book(models.Model):
    sid = models.AutoField(primary_key=True)
    title = models.CharField(verbose_name="书名",max_length=32)
    img = models.FileField(upload_to='book_imgs/', default="/book_imgs/default.jpg")
    price = models.FloatField(verbose_name="价格")
    author = models.CharField(verbose_name="作者",max_length=32,null=True)
    publish = models.CharField(verbose_name="出版社",max_length=32,null=True)
    pub_time = models.DateField(verbose_name="出版时间",null=True)
    brief = models.CharField(verbose_name="简介",max_length=200)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    category = models.ManyToManyField(to='Category')

class Book_detail(models.Model):
    sell_book = models.OneToOneField(Book,on_delete=models.CASCADE)
    status_choices = ((0, '正常销售'), (1, '已售罄'), (2, '已下架'), (3, '暂时无货'))
    status = models.SmallIntegerField(choices=status_choices, verbose_name="状态",default=0)
    book_count = models.IntegerField(verbose_name='在售书籍数量',null=True,default=1) #这里默认应该是一本



class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    payment_number = models.CharField(max_length=128, verbose_name="支付第3方订单号", null=True, blank=True)
    order_number = models.CharField(max_length=128, verbose_name="订单号", unique=True)  # 考虑到订单合并支付的问题
    actual_amount = models.FloatField(verbose_name="实付金额")
    status_choices = ((0, '交易成功'), (1, '待支付'), (2, '退费申请中'), (3, '已退费'), (4, '主动取消'), (5, '超时取消'))
    status = models.SmallIntegerField(choices=status_choices, verbose_name="状态")
    date = models.DateTimeField(auto_now_add=True, verbose_name="订单生成时间")
    pay_time = models.DateTimeField(blank=True, null=True, verbose_name="付款时间")
    cancel_time = models.DateTimeField(blank=True, null=True, verbose_name="订单取消时间")


class OrderDetail(models.Model):
    """订单详情"""
    order = models.ForeignKey("Order", on_delete=None)
    book = models.ForeignKey(Book, on_delete=None)
    original_price = models.FloatField("书籍原价")
    price = models.FloatField("折后价格")
    memo = models.CharField(max_length=255, blank=True, null=True, verbose_name="备忘录")

# 点赞评论表
class Comment(models.Model):
    cid = models.AutoField(primary_key=True)
    content = models.CharField(verbose_name="评论", max_length=200)
    book =models.ForeignKey(verbose_name='评论书籍',to='Book',to_field='sid',on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,verbose_name='评论者',on_delete=models.CASCADE)
    create_time = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    parent_comment = models.ForeignKey('self', null=True, on_delete=models.CASCADE)
    up_count = models.IntegerField(default=0)
    score = models.SmallIntegerField(null=True)


class Book_up_down(models.Model):
    bid = models.AutoField(primary_key=True)
    comment =models.ForeignKey(verbose_name='点赞评论',to='Comment',to_field='cid',on_delete=models.CASCADE,default=None)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    is_up = models.BooleanField(default=True)


class Shopping_car(models.Model):
    sid = models.AutoField(primary_key=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=None)
    book = models.ForeignKey(Book,on_delete=None)

templates/appraise.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'css/old_book.css' %} "/>
    <link rel="stylesheet" href="/static/bs/css/bootstrap.css">
    <style>
        body{
            background-color: gainsboro;
        }
        .appraise>div>img{
            width: 90px;
            height: 128px;
            box-shadow: 1px 0px 4px 2px #888888;
        }
        .appraise>div>h3{
            text-align: center;
        }
        .appraise>.start>span{
            font-size: 25px;
        }
        .appraise>.start{
            color: silver;
            cursor: pointer;
        }
        .appraise>.start>p{
            color: #3e8f3e;
            font-size: 15px;
        }
        .col-md-6{
            background-color: snow;
        }
        .appraise{
            height: 900px;
        }
    </style>
</head>
<body>
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="appraise" id="{{ book.sid }}">
            <div>
                <h3>给《{{ book.title }}》评分</h3>
            </div>
            <div class="text-center" style="padding-top: 20px">
                <img src="/media/{{ book.img }}">
            </div>
            <div class="start text-center" style="padding-top: 20px">
                <p>*请给书籍评分*</p>
                <span sid="1" class="glyphicon glyphicon-star"></span>
                <span sid="2" class="glyphicon glyphicon-star"></span>
                <span sid="3" class="glyphicon glyphicon-star"></span>
                <span sid="4" class="glyphicon glyphicon-star"></span>
                <span sid="5" class="glyphicon glyphicon-star"></span>
            </div>
            <div class="text-center" style="padding-top: 20px;">
                <textarea placeholder="一些阅读感受…" style="width: 400px;height: 100px"></textarea>
                <button class="appraise_btn btn-warning" style="width: 400px;margin-top: 100px" type="button">发表评论</button>
            </div>
            <div></div>
        </div>
    </div>
</div>
</body>
<script src="/static/js/jquery-3.2.1.min.js" type="text/javascript" charset="utf-8"></script>

<script type="text/javascript">
    var hint={
        1:'不要看',
        2:'不好看',
        3:'还可以',
        4:'好看',
        5:'非常好看'
    };

    $('.start>span').click(function () {
        $('.appraise>.start>span').css('color','silver');
        var star_numb = $(this).attr('sid');
        $('.start>p').html(hint[star_numb]).attr('score',star_numb);
        var i = 1;
        while (i<Number(star_numb)+1){
            $('span[sid="'+i+'"]').css('color','green');
            i+=1;
        }

    });




    $('.appraise_btn').click(function () {
        if($('textarea').val()){
            var text = $('textarea').val();
            var book_id = $('.appraise').attr('id');
            console.log(text,book_id);
            var star_numb = $('.start>p').attr('score');
            console.log(star_numb);
            data = {
                'appraise_text':text,
                'book_id':book_id,
                'star_numb':star_numb,
                "csrfmiddlewaretoken": '{{ csrf_token }}'
            };
            $.ajax({
                url:'',
                type:'post',
                data:data,
                success:function(data){
                    if(data.title){
                        console.log(data.title);
                        location.href = "/book_detail/"+book_id

                    }else {
                        console.log(data.msg)
                    }
                }
            });
        }else {
            alert('不允许评价为空')
        }
    })
</script>
</html>

templates/base_foot.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="x-ua-compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Title</title>
</head>
<link rel="stylesheet" href="/static/bs/css/bootstrap.css">
<link rel="stylesheet" href="{% static 'css/old_book.css' %} "/>
<body>
<div class="row">
    <div class="cont col-md-6 col-md-offset-3">
        {% block content %}

        {% endblock content %}
        <div class="foot col-md-6 col-md-offset-3 navbar navbar-default navbar-fixed-bottom">
            <ul>
                <li>
                    <a href="/home/" class="home">
                        <span class="glyphicon glyphicon-home"></span>
                        <p>首页</p>
                    </a>
                </li>
                <li><a href="/sell_book/" class="sell_book sell_in"><span class="glyphicon glyphicon-book"></span>
                    <p>卖书</p></a></li>
                <li><a href="/shop_car/" class="shop_car"><span class="glyphicon glyphicon-shopping-cart"></span>
                    <p>购物车</p></a></li>
                <li>
{#                                {{ request.user.pk }}#}

                    {% if request.user.pk %}
                        <a href="/my_zone/">
                            <span class="glyphicon glyphicon-user"></span>
                            <p>个人中心</p>
                        </a>
                    {% else %}
                        <a class="login_user" href="/login/">
                            <span class="glyphicon glyphicon-question-sign"></span>
                            <p>登录账号</p>
                        </a>
                    {% endif %}
                </li>
            </ul>

        </div>
    </div>
</div>


</body>

<script src="/static/js/jquery-3.2.1.min.js" type="text/javascript" charset="utf-8"></script>
<script src="/static/bs/js/bootstrap.min.js"></script>

<script type="text/javascript">
    var plate = function (pk,img,title,author,price) {
      st = `<div class="clearfix book_title">
            <a href="/book_detail/${ pk }" class="clearfix ">
                <div class="pull-left thumbnail">
                    <img src="media/${ img }">
                </div>
                <div class="pull-left">
                    <p>${ title }</p>
                    <p>${ author }</p>
                    <p><span>¥&nbsp</span>${ price }</p>
                </div>
            </a>
        </div>
    `;
        return st
    };
    {#动态加载书籍信息#}
    var page_numb = 2;
    $('.more_book').click(function () {
        $.ajax({
            url:'',
            method:'post',
            data:{
                'page':page_numb,
                "csrfmiddlewaretoken": '{{ csrf_token }}',
            },
            success:function (data) {
                if(data.title){
                    var book_list = JSON.parse(data.title);
                    var index = 0;
                    var elements = '';
                    while (index<book_list.length) {
                        obj = book_list[index].fields;
                        elements+=plate(book_list[index].pk,obj.img,obj.title,obj.author,obj.price);
                        index+=1
                    }
                    $('.book_list').append(elements)
                }else {
                    $('.more_book').text(data.msg)
                }

            }
        });
        page_numb+=1
    });


    {#首页书籍分类#}
    function get_bgc() {
        var bgcolor=[
            '#D24D57','#26A65B','#EB7347','#2C3E50','#84AF9B','#FC9D99','#AEDD81' ,'#00CCFF' ,'#D0D0D0'
        ];
        var num = Math.round(Math.random()*(bgcolor.length));
        return bgcolor[num]
    }


    window.onload = function () {
        var numbs = $('.recommend_cate>ul>li');
        for(var li_ele in numbs){
        $('.recommend_cate>ul>li:eq('+li_ele+')').css('background-color',get_bgc())
        }

        {#底部栏添加active#}
        url = location.href.split('/');
        if(!url[3]){
            $(".home").addClass('home_active');
        }else {
            $("."+url[3]).addClass('home_active');

        }


        {#书籍分类#}
        var cates = $('.book_cate>ul>li');
        for(ele in cates) {
            var colors = [
                'list-group-item-success','list-group-item-info',
                'list-group-item-warning','list-group-item-danger'
            ];
            {#console.log(typeof  colors.length);#}
            {#以数组长度产生随机数#}
            num = Math.round(Math.random()*(colors.length));

            $('.book_cate>ul>li:eq('+ele+')').addClass(colors[num])
        }
    };



        $("#img").change(function () {
            {#alert('dd');#}
            // 获取用户选中的文件对象
            var file_obj = $(this)[0].files[0];
            // 获取文件对象的路径

            var reader = new FileReader();
            reader.readAsDataURL(file_obj);
            console.log('reader.result',reader.result);
            // 修改img的src属性 ，src=文件对象的路径
            reader.onload = function () {
                $("#avatar_img").attr("src", reader.result)
            };
        });

    $('.sub_btn').click(function () {

        var formdata = new FormData();//文件传输对象
        var request_data = $("#form").serializeArray();
        $.each(request_data, function (index, data) {
            formdata.append(data.name, data.value)
        });
        {#    这里是从管道取数据 。#}
        formdata.append("book_img", $("#img")[0].files[0]);



        formdata.append("csrfmiddlewaretoken", '{{ csrf_token }}');
        {#console.log($("#img")[0].files[0]);#}
        $.ajax({
            url: '',
            method: 'post',
            contentType: false,
            processData: false,
            data: formdata,
            success: function (data) {
                console.log(data);
                if (data.title) {
                    location.href = '/sell_in/';
                    console.log(data.title)
                } else {
                    {#console.log(data.msg);#}
                    $.each(data.msg, function (field, error_list) {
                        $('#id_' + field).parent().next().html(error_list[0]);  //next同胞标签
                    })
                }
            }
        })
    });


        //通过jquery控制模态框弹出
    $(function(){
        //通过jquery控制模态框弹出
        $('.delete').click(function(){
            edit_id = $(this).attr('id');
            title_book = $('#'+edit_id+' p:nth-child(2)').text();
            console.log('edit_id',edit_id);
            console.log('edit_id11',{{book.pk}});

            edit_book = $('.first>div>p:nth-child(2)').text();
            $('#myModalLabel').text('是否下架'+title_book);
            $('.modal-footer>button').attr('id',edit_id);

            $('#myModal').modal({
                {#模态框#}
                keyboard:false
            });


        $('.modal-footer>button').click(function(){
            console.log('ds',$(this).attr('id'));
            book_id = $(this).attr('id');
            if($(this).text()=='确定'){
                location.href = '/sell_in_del/'+book_id
            }
            if($(this).text()=='关闭'){
                location.href = '/sell_in'
            }


        });
        });


    })




</script>


</html>

templates/book_detail.html
{% load staticfiles %}
{% load my_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="x-ua-compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Title</title>
</head>
<link rel="stylesheet" href="/static/bs/css/bootstrap.css">
<link rel="stylesheet" href="{% static 'css/old_book.css' %} "/>
<body>
<div class="row">
    <div class="cont col-md-6 col-md-offset-3">

        <div class="detail">
            <div class="detail_img thumbnail">
                <img src="/media/{{ book.img }}">
            </div>
            <div class="detail_content">
                <h2>{{ book.title }}</h2>
                <hr>
                <p>价格：{{ book.price }}</p>
                <p>品相：良好</p>
                <p>作者：{{ book.author }}</p>
                <p>出版社：{{ book.publish }}</p>
            </div>
            <div class="detail_score">
                <hr>
                {% if score %}
                    <p>综合评分 : {% detail_star_numb score %}</p>
                {% else %}
                    <p>暂时没有人为这本书打分</p>
                {% endif %}


                <hr>
            </div>
            <div class="detail_brief">
                <h2>图书简介</h2>
                <hr>
                <p>{{ book.brief }}</p>
            </div>
            <div>
                <h2>评论</h2>
                <div>
                    {% for com in comment_list %}
                        {% if not com.parent_comment %}

                            <div class="book_detail"  comment="{{ com.cid }}">
                                <p>
                                    <span>{{ com.user }}</span>
                                    {% if com.score %}
                                        <span>{% star_numb com.score %} </span>
                                    {% endif %}
                                </p>
                                <p> -- {{ com.content }}</p>
                                <div id="{{ com.pk }}">
                                    <a href="/comment_reply/{{ book.pk }}/{{ com.pk }}"><img src='/static/img/comment_write.png'></a>
                                    <a class="diggit"><img src='/static/img/diggit.png'><span>{{ com.up_count }}</span></a>
                                    <a class="ch_comt_btn"><img src='/static/img/comment_load.png'></a>
                                </div>
                                <hr>
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
        </div>



        <div id="ship_car" class="foot col-md-6 col-md-offset-3 navbar navbar-default navbar-fixed-bottom">
            <ul>
                <li>
                    <a href="/home/" class="home">
                        <span class="glyphicon glyphicon-home"></span>
                        <p>首页</p>
                    </a>
                </li>
                <li class="pull-right">
                    {% if book.book_detail.status == 1 %}
                        <a class="not_click btn btn-warning car">
                            暂时无货
                        </a>
                    {% else %}
                        <a href="/shipping_car/{{ book.pk }}" class="btn btn-warning car">
                            加入购物车
                        </a>
                    {% endif %}
                </li>
            </ul>
        </div>
        <div style="height: 100px"></div>

    </div>



</body>
<script src="/static/js/jquery-3.2.1.min.js" type="text/javascript" charset="utf-8"></script>
<script type="text/javascript">

    $('.diggit').click(function () {
        comment_id = $(this).parent().attr('id');
        $.ajax({
            url:'/diggit/',
            method:'post',
            data:{
                "comment_id":comment_id,
                "csrfmiddlewaretoken": '{{ csrf_token }}'
            },
            success:function (data) {
                if(data.title){
                    $('#'+comment_id+'>.diggit').children('span').text(data.title)
                }else {
                    console.log('msg',data.msg)
                }
            }
        })
    });

    function add_comment_child(user,date,content){
        var st = `
                         <div  class="child_comt">
                            <p>
                                <span>${user}</span>
                                <span>${date}</span>
                            </p>
                            <p>
                                <span>${content}</span>
                            </p>

                        </div>
                        <hr>


                        `;
        return st
    }

    function child_title(len,child){
        var plate = `<div class='comment_reply'>
                        <p>有${len}条留言</p>
                        ${child}
                        <div >
                            <hr class="hrLine" style="width:45%;"/>  <span class='comt_close'>收起评论</span>  <hr class="hrLine" style="width:45%;"/>
                        </div>
                    </div>`;
        return plate
    }



    $('.ch_comt_btn').click(function () {
        var parent_comt = $(this).parent().attr('id');
        $('.comment_reply').remove();
        $.ajax({
            url: "",
            method: "post",
            data :{
                'parent_comt':parent_comt,
                "csrfmiddlewaretoken": '{{ csrf_token }}'
            },
        success:function (data) {
                console.log('data',data);
                if(data){
                    var i = 0;
                    var plate = '';
                    while (i<data.length){
                        plate += add_comment_child(data[i][2],data[i][1],data[i][0]);
                        i+=1;
                    }

                    $('#'+parent_comt).parent().append(child_title(data.length,plate))
                }
        }
        })
    });


        $('.book_detail').on('click','.comt_close', function () {
           $(this).parent().parent().remove();
        })




</script>
</html>

templates/book_list.html
{% extends  'home.html' %}
{% block book_list %}
    <div class="book_list">

        {% for book in books %}
            <div class="clearfix book_title">
                <a href="/book_detail/{{ book.pk }}" class="clearfix ">
                    <div class="pull-left thumbnail">
                        <img src="media/{{ book.img }}">
                    </div>
                    <div class="pull-left">
                        <p>{{ book.title }}</p>
                        <p>{{ book.author }}</p>
                        <p><span>¥&nbsp</span>{{ book.price }}</p>
                    </div>
                </a>
            </div>

        {% endfor %}

    </div>
    <hr>
    <p class="more_book">
        <img src="/static/img/angle-double-down.png">
        再多来点儿
    </p>
{% endblock book_list%}


<script src="/static/js/jquery-3.2.1.min.js" type="text/javascript" charset="utf-8"></script>
<script type="text/javascript">




</script>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="x-ua-compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="/static/bs/css/bootstrap.css">

    <title>登录页面</title>

</head>
<body>
    <div class="login row">
        <div class="col-md-6 col-md-offset-3">
            <h2>登录页面</h2>
            <hr>
            <form method="post" novalidate>
                {% csrf_token %}
                {% for field in form %}
                    <div class="input-group input-group-lg" style="margin-top: 50px">
                        <span class="input-group-addon" id="sizing-addon1">{{field.label}}</span>
                        {{ field }}
                    </div>
                    <span class="login_error pull-right" style="color: red">
                          {% if field.label == '账号' %}
                              <span>{{ clean_error.0 }}</span>
                          {% endif %}
                        {{ field.errors.0 }}
                    </span>
                {% endfor %}
                <div class="btn success pull-right">
                    <a href="/register/">还没有账号，注册账号</a>
                    <input type="submit" name="publish" class="form-control" required="" id="id_publish">
                </div>
            </form>
        </div>


    </div>

</body>
<script src="/static/js/jquery-3.2.1.min.js" type="text/javascript" charset="utf-8">

</script>
<script type="text/javascript">

    $('.btn').click(function () {
        $('.login_error').remove()
    })

</script>
</html>

templates/my_balance.html
{% extends 'my_zone.html' %}
{% block zone %}
    <div id="zone_type"  class="my_balance">
        <p>——账户余额——</p>
        <p class="yue">0.00</p>
        <span><button class="btn-default">充值余额</button></span>
    </div>

{% endblock %}

templates/my_bookrack.html
{% extends 'my_zone.html' %}
{% block zone %}
    <div id='zone_type' class="my_bookrack">
        <div class="rack_list"></div>
        {% for order in order_list %}
            <div class="rack ">
                <div class="book-r clearfix">
                    <a href="book_detail/{{ order.book.sid }}">
                        <div class="clearfix">
                            <img class="pull-left" src="media/{{ order.book.img }}">
                            <div  class="pull-left">
                                <p style="font-size: 15px">{{ order.book.title }}</p>
                                <p style="padding-left: 20px">{{ order.book.author }}</p>
                                <p class="score" style="padding-left: 20px">
                                    <object>
                                        <a href="/appraise/{{ order.book.sid }}">
                                            <span class="glyphicon glyphicon-star-empty"></span>评分
                                        </a>
                                    </object>
                                </p>
                            </div>
                            <div class="seller pull-right">
                                <p>{{ order.book.user }}</p>
                            </div>
                        </div>

                    </a>


                </div>
            </div>

            <hr>
        {% endfor %}
    </div>

{% endblock %}

templates/sell_in_edit.html
{% extends 'base_foot.html' %}
{% block content %}
    <div class="edit_book">
        <div>
            <form id="form" novalidate="">
                {% csrf_token %}

                <div class="input-group input-group-lg">
                    <label class="input-group-addon" id="sizing-addon1">书名</label>
                    <input type="None" name="title" class="form-control input-group input-group-lg" maxlength="32" value="{{ book_obj.title }}" required="" id="id_title">
                </div>
                <span class="login_error pull-right" style="color: red">


                    </span>


                <div class="input-group input-group-lg">
                    <label class="input-group-addon" id="sizing-addon1">价格</label>
                    <input type="None" name="price" class="form-control" value="{{ book_obj.price }}" required="" id="id_price">
                </div>
                <span class="login_error pull-right" style="color: red">


                    </span>


                <div class="input-group input-group-lg">
                    <label class="input-group-addon" id="sizing-addon1">作者</label>
                    <input type="None" name="author" class="form-control" value="{{ book_obj.author }}" required="" id="id_author">
                </div>
                <span class="login_error pull-right" style="color: red">


                    </span>


                <div class="input-group input-group-lg">
                    <label class="input-group-addon" id="sizing-addon1">出版社</label>
                    <input type="None" name="publish" class="form-control" value="{{ book_obj.publish }}"  required="" id="id_publish">
                </div>
                <span class="login_error pull-right" style="color: red">


                    </span>


                <div class="input-group input-group-lg">
                    <label class="input-group-addon" id="sizing-addon1">简介</label>
                    <input type="None" name="brief" class="form-control" value="{{ book_obj.brief }}" required="" id="id_brief">
                </div>
                <span class="login_error pull-right" style="color: red">


                    </span>


                <div class="input-group input-group-lg">
                    <label class="input-group-addon" id="sizing-addon1">出版时间</label>
                    <input type="date" name="pub_time" class="form-control"  value="{{ book_obj.pub_time | date:'Y-m-d'  }}" required="" id="id_pub_time">
                </div>
                <span class="login_error pull-right" style="color: red">


                    </span>



                <div class="form-group">
                    <label for="img">
                        <p>&gt;添加书籍封面</p>
                        <img id="avatar_img" width="100" src="media/{{book_obj.img}}">
                    </label>
                    <input type="file" id="img" name="book_img" style="display: none">
                </div>

            </form>
            <input type="submit" value="上架" class="edit_btn sub_btn form-control">
            <div class="search_books"></div>
        </div>
    </div>

    <script src="/static/js/jquery-3.2.1.min.js" type="text/javascript" charset="utf-8"></script>
    <script src="/static/bs/js/bootstrap.min.js"></script>

    <script type="text/javascript">
        $('.sub_btn').click(function () {

            var formdata = new FormData();//文件传输对象
            var request_data = $("#form").serializeArray();
            $.each(request_data, function (index, data) {
                formdata.append(data.name, data.value)
            });
            {#    这里是从管道取数据 。#}
            formdata.append("book_img", $("#img")[0].files[0]);
            console.log( $("#img")[0].files[0]);


            formdata.append("csrfmiddlewaretoken", '{{ csrf_token }}');
            {#console.log($("#img")[0].files[0]);#}
            $.ajax({
                url: '',
                method: 'post',
                contentType: false,
                processData: false,
                data: formdata,
                success: function (data) {
                    console.log(data);
                    if (data.title) {
                        {#location.href = '/sell_in/'#}
                        console.log(data.title)
                    } else {
                        {#console.log(data.msg);#}
                        $.each(data.msg, function (field, error_list) {
                            $('#id_' + field).parent().next().html(error_list[0]);  //next同胞标签
                        })
                    }
                }
            })
        });



    </script>

{% endblock %}